Add support for etcd client version 3
devopsfaith/krakend-etcd pull request #2
Opened 2019-04-16 13:01 UTC by khvysofq

Hi, kpacha. This PR is primarily to support the functionality of the ETCD clientv3. The major changes are as follows

- Add `clientv3.go`、`clientv3_testing.go` in the root of the source code.
- Move some common parts into the `config.go`

Both modes are supported through profile configuration, just add `"client_version": "v3"` option in `extra_config`

```json
"extra_config": {
    "github_com/devopsfaith/krakend-etcd": {
        "machines": [ "http://192.168.110.111:2379" ],
		"client_version": "v3",
        "options": {
            "dial_timeout": "5s",
            "dial_keepalive": "30s",
            "header_timeout": "1s"
        }
    }
}
```

- `"client_version": "v3"` using the etcd clientv3
- `"client_version": "v2"` using the etcd clientv2 (old version)

The default value is `v2`, if you are not set `"client_version"`. I have tested in my local machines.

---

Among other things, there is one small problem. I used go mod to manage my go packages. but in the original code of the `example/main.go`, the `github.com/devopsfaith/krakend-etcd`(v 3.3.10 or newer version) and `github.com/devopsfaith/krakend-viper` conflict when load package `github.com/ugorji/go`

- `github.com/devopsfaith/krakend-etcd`(v 3.3.12) need `github.com/ugorji/go@v1.1.1`
- `github.com/devopsfaith/krakend-viper` auto need `github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8`

They need the same package, but not the same directory and not the same version. The go mod can't handle this situation. see [https://github.com/spf13/viper/issues/658](https://github.com/spf13/viper/issues/658)

So, in the `example/main.go`, I can only change `github.com/devopsfaith/krakend-viper` to `github.com/devopsfaith/krakend/config`

2019-04-21 16:07 UTC, kpacha requested changes
This is a great contribution!

Please, check my comments

2019-04-21 16:07 UTC, kpacha commented on config.go
> +	} else {
the else statement is not required since the other path is already finished

2019-04-21 16:07 UTC, kpacha commented on config.go
> +		log.Warnf("")
remove this call to the prometheus logger

2019-04-21 16:07 UTC, kpacha commented on clientv3.go
> +		select {
remove the select statement. it's ok to just extract the next message from the channel and let the goroutine wait for it

```
for _ = range watch {
	ch <- struct{}{}
}
```

2019-04-21 16:07 UTC, kpacha commented on example/krakend.json
> +                        "github.com"
we defined a "non compliant service name" in order to make it clear that these should be etcd keys

2019-04-21 16:07 UTC, kpacha commented on example/main.go
> +	"github.com/khvysofq/krakend-etcd"
this import points to the fork

2019-04-21 16:07 UTC, kpacha commented on subscriber.go
> +
please, remove the tab

2019-04-21 16:07 UTC, kpacha commented on example/main.go
> +	"github.com/khvysofq/krakend-etcd"
also, please run the [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports) command on the code

2019-04-22 02:49 UTC, khvysofq commented
HI, thanks for you PR review, I have solved, See the commits.

2019-04-22 10:41 UTC, kpacha commented on config.go
> +	if result != "v2" && result != "v3" {
just in case, I'd check the type conversion

```
	result, ok := value.(string)
	if !ok || (result != "v2" && result != "v3") {
```

2019-04-22 10:42 UTC, kpacha commented on clientv3.go
> +	// watch := c.keysAPI.Watcher(prefix, &etcd.WatcherOptions{AfterIndex: 0, Recursive: true})
this comment is not required

2019-04-22 10:44 UTC, kpacha commented
@khvysofq I've added two more comments regarding two minor details and I think it's almost ready to be merged.

Again, thanks for the contribution to the project

2019-04-23 02:42 UTC, khvysofq commented
The KrakenD is a very promising project . I am honored to contribute to this project. Anyway if you have any suggestions for this PR, please point it out. I want do it better as krakenD project do.

2019-04-23 08:44 UTC, kpacha approved these changes

2019-04-23 08:45 UTC, merged